### ISSUE TITLE
Calcul du prix

### ISSUE THREAD

**Issue by paulrufin** [jacquestremblay/inf3080-a2019-tp1#4]
Bonjour M. Hammad, 

Je n'arrive pas à me décider sur la méthode de calcul du prix des soumissions.
En ce moment je le fais dans un SELECT ([04a_query.sql](https://github.com/jacquestremblay/inf3080-a2019-tp1/blob/master/04a_query.sql)) mais idéalement je pense que le calcul ne devrait même pas se faire dans la BD mais plus dans le code du 'site internet' en arrière plan.

L'autre option serait de mettre le prix au moment du INSERT mais la encore le calcul devrait se faire en arrière plan ou bien après l'INSERT dans 02_charger.

Que suggérez-vous ?

Merci

**Comment by ammarhamad** [comment]
Bonjour 
Dans la base de données, on garde les données et tout information on utilise des scripts et des fonctions qui seront faire en arrière plan comme vous dites.

**Comment by paulrufin** [comment]
> Bonjour
> Dans la base de données, on garde les données et tout information on utilise des scripts et des fonctions qui seront faire en arrière plan comme vous dites.

Bonjour,

Merci pour votre réponse rapide. Donc si je comprend bien, on simule une fonction en arrière et on hardcode le montant dans notre table soumission ?

**Comment by ammarhamad** [comment]
Oui

Ammar

Sent from my iPhone

On Oct 18, 2019, at 8:40 AM, paulrufin <notifications@github.com> wrote:

﻿

Bonjour
Dans la base de données, on garde les données et tout information on utilise des scripts et des fonctions qui seront faire en arrière plan comme vous dites.

Bonjour,

Merci pour votre réponse rapide. Donc si je comprend bien, on simule une fonction en arrière et on hardcode le montant dans notre table soumission ?

**Comment by paulrufin** [comment]
Excellent Merci !
